<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title> Erro fatal - Solicite suporte técnico </title>
</head>
<body>
    <h1> Erro fatal </h1>
    <p>
        Não foi possível executar a aplicação. Tente de novo mais tarde.
    </p>
    <p>
        O log de erro foi enviado para a equipe de suporte.
    </p>
</body>
</html>
