<h2 class="noDisplay"> Menu principal </h2>
<div class="main-nav">
    <ul class="clearfix">
        <li><a href="<?=$this->url(array('controller' => 'customer', 'action' => 'list'), 'admin', true); ?>" title="Customers"> Clientes </a></li>
        <li><a href="<?=$this->url(array('controller' => 'catalog', 'action' => 'list'), 'admin', true); ?>" title="Catalog"> Produtos </a></li>
        <li><a href="/" title="Homepage"> Loja </a></li>
    </ul>
</div>